---
name: 'SlackNotify Action'
description: 'A GitHub Action for sending notifications to Slack'
author: 'Anthony Yung <antyung41@gmail.com>'
branding:
  icon: 'activity'
  color: 'white'

inputs:
  webhook_url:
    description: 'The Slack webhook URL'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send Slack Notification
      shell: bash
      run: |
        $(which sudo) apt-get install -y bash git curl jq || { $(which sudo) apt-get update && $(which sudo) apt-get install -y bash git curl jq; }
        curl -fsSL https://raw.githubusercontent.com/sudo88com/slacknotify-action/main/notify_slack.sh | bash -s -- send
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_JOB_STATUS: ${{ job.status }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }}
        GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        GITHUB_REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
        GITHUB_REPOSITORY_NAME: ${{ github.repository }}
