---
name: Lint Code Base

on:
  push:

jobs:
  lint:
    name: Lint Bash and YAML files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint
        run: |
          for file in $(find . -name "*.yml" -o -name "*.yaml"); do
            echo "Checking $file"
            yamllint "$file"
          done
          echo "YAML linting success"

      - name: Lint Bash scripts
        run: |
          for file in $(find . -name "*.sh"); do
            echo "Checking $file"
            bash -n "$file"
          done
          echo "Bash script linting success"
